### Criando Drive

In [ ]:
#from google.colab import drive

#drive.mount('/content/drive')

### Importando CSV

In [ ]:
import pandas as pd 
import numpy as np
import datetime as datetime


dado = pd.read_csv("Base de atividades tratadas.csv", sep=";")

dado.shape

(178941, 10)

In [ ]:
# prepocessing

# arrumar as colunas e os tipos de dados antes de fazer a analise

In [ ]:
dado.dtypes

id                     int64
brand_id               int64
store_id               int64
user_id                int64
data                  object
first_interaction       bool
interacted_at         object
object_id              int64
object_type           object
value                float64
dtype: object

In [ ]:
dado['interacted_at'] = pd.to_datetime(dado['interacted_at'])

In [ ]:
dado[['id','brand_id','store_id','user_id']] = dado[['id','brand_id','store_id','user_id']].astype(str)

In [ ]:
#reg = dado["interacted_at"]
#coluna_data = reg.str.extract('(\d{4})', expand=False)

#coluna_data

In [ ]:
dado.head()

id brand_id store_id  ... object_id object_type  value
0  499328473        2      356  ...        26      Reward    6.0
1  499331703        2      356  ...   4327945      Review    0.0
2  499332964        2      356  ...   4327970      Review    0.0
3  499340669        2      356  ...        26      Reward    6.0
4  499341957        2      356  ...  55566544    Purchase   41.2

[5 rows x 10 columns]

### Analise dos Dados

In [ ]:
dado[dado['first_interaction']== True]['user_id'].unique()

array(['9056365', '3933796', '6923028', ..., '9104814', '11934655',
       '11934809'], dtype=object)

In [ ]:
# quantidade de lojas

# dado[(dado["store_id"]& (dado["object_type"] == "Review")].value_counts()


lj_com_review = dado[dado['object_type']=='Review']

vendas_lojas = dado[dado['object_type']=='Purchase']



verificando quantidade de lojas com reviews e compras 


2375    
356     
376     
377     
383     
3920    
4319    
4828    
5294    
602      

In [ ]:
lj_com_review["store_id"].value_counts().sort_index()


2375     962
356     1718
376      807
377     1064
383     1466
3920     942
4319    2170
4828    1873
5294    1436
602      548
Name: store_id, dtype: int64

In [ ]:
vendas_lojas["store_id"].value_counts().sort_index()

2375    12014
356     21367
376     13575
377     13511
383     14496
3920     7341
4319    24680
4828    18448
5294    12486
602      7750
Name: store_id, dtype: int64

In [ ]:
lj_rv = lj_com_review["store_id"].value_counts().sort_index().unique()

lj_rv




array([ 962, 1718,  807, 1064, 1466,  942, 2170, 1873, 1436,  548])

In [ ]:
vd_lj = vendas_lojas["store_id"].value_counts().sort_index().unique()

vd_lj



array([12014, 21367, 13575, 13511, 14496,  7341, 24680, 18448, 12486,
        7750])

In [ ]:
loj = [2375,356, 376, 377, 383, 3920, 4319, 4828, 5294, 602]
for vd, lj, loj in zip(vd_lj, lj_rv, loj):
  s = vd / lj
  print("a loja {} tem taxa de {}% de reviws ".format(loj, s))
  

a loja 2375 tem taxa de 12.488565488565488% de reviws 
a loja 356 tem taxa de 12.437136204889406% de reviws 
a loja 376 tem taxa de 16.821561338289964% de reviws 
a loja 377 tem taxa de 12.698308270676693% de reviws 
a loja 383 tem taxa de 9.8881309686221% de reviws 
a loja 3920 tem taxa de 7.792993630573249% de reviws 
a loja 4319 tem taxa de 11.373271889400922% de reviws 
a loja 4828 tem taxa de 9.84943940202883% de reviws 
a loja 5294 tem taxa de 8.694986072423399% de reviws 
a loja 602 tem taxa de 14.142335766423358% de reviws 


In [ ]:

mensagens = dado[(dado['store_id']== 4828) & (dado['object_type']=='Review')]["data"].unique()
mensagens

array([], dtype=object)

In [ ]:
dado[dado['first_interaction']== True]

id brand_id store_id  ... object_id object_type  value
10      499431394        2      356  ...  55613847    Purchase   18.9
15      499436962        2      356  ...  55617711    Purchase   55.7
17      499439089        2      356  ...  55619408    Purchase   24.9
24      499447563        2      356  ...  55624870    Purchase   58.8
26      499450270        2      356  ...  55626785    Purchase   25.4
...           ...      ...      ...  ...       ...         ...    ...
178916  528248169        2      377  ...  69879772    Purchase   43.3
178925  528559313        2      377  ...  69906441    Purchase   28.5
178934  541522465        2     2375  ...  74297858    Purchase   24.9
178937  541527545        2     2375  ...  74300669    Purchase   22.9
178940  541530256        2     2375  ...  74302043    Purchase   43.8

[56528 rows x 10 columns]

In [ ]:
# criando array de clientes que tiveram uma primeira interação
list_cliente_first = dado[dado['first_interaction']== True]['user_id'].unique()

In [ ]:
list_cliente_first

array(['9056365', '3933796', '6923028', ..., '9104814', '11934655',
       '11934809'], dtype=object)

In [ ]:
## pegando as vendas destes clientes

vendas  = dado[dado['user_id'].isin(list_cliente_first)]


In [ ]:
vendas

id brand_id store_id  ... object_id object_type  value
1       499331703        2      356  ...   4327945      Review    0.0
10      499431394        2      356  ...  55613847    Purchase   18.9
14      499435472        2      356  ...   4329070      Review    0.0
15      499436962        2      356  ...  55617711    Purchase   55.7
16      499438586        2      356  ...  55619072    Purchase   24.9
...           ...      ...      ...  ...       ...         ...    ...
178933  541520825        2     2375  ...   4944821      Review    0.0
178934  541522465        2     2375  ...  74297858    Purchase   24.9
178937  541527545        2     2375  ...  74300669    Purchase   22.9
178938  541528217        2     2375  ...  74301028    Purchase   24.5
178940  541530256        2     2375  ...  74302043    Purchase   43.8

[104447 rows x 10 columns]

Maiores frequencias de clientes

In [ ]:
vendas['user_id'].value_counts()

4903322     68
1711189     58
3846196     55
9542884     51
3525314     49
            ..
8255817      1
11312614     1
9128690      1
6314730      1
9493398      1
Name: user_id, Length: 54743, dtype: int64

In [ ]:

vendas[vendas['user_id']== '8483188']['first_interaction'].value_counts()

False    17
True      4
Name: first_interaction, dtype: int64

In [ ]:
a  = vendas[(vendas['user_id']== '8483188') & (vendas['object_type']=='Purchase')].sort_values('interacted_at')

In [ ]:
a

id brand_id store_id  ... object_id object_type  value
35551   463517380        2     4319  ...  47770254    Purchase  22.10
600     503623481        2      376  ...  57178970    Purchase  23.90
75614   504007471        2      376  ...  57385644    Purchase  29.90
36747   445948069        2      376  ...  46082277    Purchase  21.00
440     499509090        2     4828  ...  55667273    Purchase  22.90
4132    500660671        2     4828  ...  56147697    Purchase  38.89
13373   500938272        2      376  ...  56207951    Purchase  21.90
95103   510146985        2      376  ...  60706544    Purchase  49.90
32855   495982205        2     4828  ...  53689265    Purchase  21.00
171086  538946450        2     4319  ...  73441303    Purchase  27.00

[10 rows x 10 columns]

Encontrada incosistencia nos dados, pois o cliente 8483188, na data 2019-09-06 20:18:00 está registrada primeira interação com a loja 4828, porém em 2019-06-22 18:35:00 possuem registros de compra do cliente.

In [ ]:
for data in a['data']:
  print(data)

{"total_value":"R$ 22,10","brand_name":"Spoleto","count":1}
{"total_value":"R$ 23,90","brand_name":"Spoleto","count":1}
{"total_value":"R$ 29,90","brand_name":"Spoleto","count":1}
{"total_value":"R$ 21,00","brand_name":"Spoleto","count":1}
{"total_value":"R$ 22,90","brand_name":"Spoleto","count":1}
{"total_value":"R$ 38,89","brand_name":"Spoleto","count":2}
{"total_value":"R$ 21,90","brand_name":"Spoleto","count":1}
{"total_value":"R$ 49,90","brand_name":"Spoleto","count":2}
{"total_value":"R$ 21,00","brand_name":"Spoleto","count":1}
{"total_value":"R$ 27,00","brand_name":"Spoleto","count":1}


In [ ]:
vendas[(vendas['user_id']== '4903322')]['interacted_at'].min()

Timestamp('2019-01-06 15:20:00')

In [ ]:
vendas[(vendas['user_id']== '4903322') & (vendas['store_id']=='376')].sort_values('interacted_at')

id brand_id store_id  ... object_id object_type  value
22791   468089599        2      376  ...        26      Reward    6.0
22840   468227457        2      376  ...  48227922    Purchase   28.9
22794   468237384        2      376  ...        26      Reward    6.0
130077  522308919        2      376  ...  67031519    Purchase   56.8
113946  516231068        2      376  ...  64014639    Purchase   52.9
128144  520125006        2      376  ...     31498       Offer    0.0
128201  520126053        2      376  ...  65940182    Purchase   65.2
124028  520436462        2      376  ...        26      Reward    6.0
124029  520437672        2      376  ...  66106991    Purchase   48.4
147671  530169034        2      376  ...  70250554    Purchase   24.9

[10 rows x 10 columns]

In [ ]:
vendas[(vendas['user_id']== '4903322') ]['store_id'].unique()

array(['4319', '376'], dtype=object)

In [ ]:
vendas[(vendas['user_id']== '4903322') & (vendas['first_interaction']==True)]

id brand_id store_id  ... object_id object_type  value
22791  468089599        2      376  ...        26      Reward    6.0

[1 rows x 10 columns]

In [ ]:
# vendas['interacted_at'] = pd.to_datetime(vendas['interacted_at'])

In [ ]:
vendas['interacted_at']

1        2019-06-22 00:11:00
10       2019-06-22 15:20:00
14       2019-06-22 15:32:00
15       2019-06-22 15:35:00
16       2019-06-22 15:40:00
                 ...        
178933   2019-10-25 00:27:00
178934   2019-10-25 00:32:00
178937   2019-10-25 00:48:00
178938   2019-10-25 00:50:00
178940   2019-10-25 00:56:00
Name: interacted_at, Length: 104447, dtype: datetime64[ns]

In [ ]:
vendas["user_id"].astype(str)
vendas["user_id"].describe()

count      104447
unique      54743
top       4903322
freq           68
Name: user_id, dtype: object

In [ ]:
# teste.loc[teste.user_id == "8483188"]



In [ ]:
# após primeira interação com a marca mais de 40% retornam  #54743 total

vendas["user_id"].min()

'10000083'

In [ ]:


remove_reviews = vendas.loc[(vendas['object_type'] == "Review")]

dt_sem_reviews = vendas.drop(remove_reviews.index)

dt_sem_reviews["user_id"].describe()

count       95200
unique      54743
top       4903322
freq           58
Name: user_id, dtype: object

In [ ]:
reviews = vendas[vendas['object_type']== "Review"]['user_id'].unique()   #id de quem tem review
reviews_completas = vendas[vendas['object_type']== "Review"]     

dt_dado = vendas.drop(reviews_completas.index)

dt_dado[dt_dado["user_id"].isin(reviews)]

id brand_id store_id  ... object_id object_type  value
34      499471489        2      356  ...  55640032    Purchase   74.6
62      499435712        2      376  ...  55616874    Purchase   17.0
63      499438632        2      376  ...  55618189    Purchase   22.9
66      499441211        2      376  ...  55620529    Purchase   17.0
75      499458008        2      376  ...  55632282    Purchase   19.9
...           ...      ...      ...  ...       ...         ...    ...
178899  528610661        2      376  ...  69933318    Purchase   19.4
178901  528615415        2      376  ...  69935823    Purchase   23.0
178923  528558348        2      377  ...     33596       Offer    0.0
178924  528558767        2      377  ...  69906231    Purchase   24.3
178932  541516737        2     2375  ...  74294672    Purchase   17.0

[26730 rows x 10 columns]

In [ ]:
dt_dado["user_id"].value_counts()

4903322     58
3846196     55
1711189     53
9542884     51
3525314     49
            ..
9617313      1
11808422     1
9570151      1
11463843     1
9493398      1
Name: user_id, Length: 54743, dtype: int64

vendas de clientes que comentam 26730 
vendas totais 95200
nao comentam 68470

In [ ]:
68470/46653  # Nao fazem review

1.4676440957709043

In [ ]:
26730/8086

3.305713579025476

In [ ]:
vendas[vendas["object_type"]!="Review"]["user_id"].isin(reviews).value_counts()

False    68470
True     26730
Name: user_id, dtype: int64

In [ ]:
# reviews.value_counts()

In [ ]:
cliente1 = dt_sem_reviews.loc[dt_sem_reviews.user_id == "4903322"].sort_values('interacted_at') 

cliente1.loc[(cliente1["object_type"]=="Reward")].sort_values('interacted_at')


id brand_id store_id  ... object_id object_type  value
66840   423913203        2     4319  ...        26      Reward    6.0
22791   468089599        2      376  ...        26      Reward    6.0
22794   468237384        2      376  ...        26      Reward    6.0
154672  533200499        2     4319  ...        26      Reward    6.0
50904   447322457        2     4319  ...        26      Reward    6.0
105460  513167358        2     4319  ...        26      Reward    6.0
8186    500000482        2     4319  ...        26      Reward    6.0
11235   502690120        2     4319  ...        26      Reward    6.0
38501   495621938        2     4319  ...        26      Reward    6.0
111836  515373176        2     4319  ...        26      Reward    6.0
118880  517883326        2     4319  ...        26      Reward    6.0
124028  520436462        2      376  ...        26      Reward    6.0
142430  526545606        2     4319  ...        26      Reward    6.0
176720  542972517        2     4319  ...        26      Reward    6.0
134574  523677554        2     4319  ...        26      Reward    6.0

[15 rows x 10 columns]

In [ ]:
cl_obj = "cliente1"
qtd = [1,5,10,15]
lalal = [1,2,3,4,5,6,7,8]
cl_data = cliente1["interacted_at"].unique()

In [ ]:
dt2 = dado.loc[(dado['object_type'] == "Review")]
dado = vendas.drop(remove_reviews.index)

dado["object_type"].value_counts()


Purchase    86183
Offer        4847
Reward       4170
Name: object_type, dtype: int64

In [ ]:
valores_c1 = cliente1["interacted_at"].value_counts().sort_index()

valores_c1



2019-01-06 15:20:00    1
2019-03-05 16:51:00    1
2019-03-10 20:10:00    1
2019-04-04 15:24:00    1
2019-04-04 15:29:00    1
2019-04-05 15:37:00    1
2019-04-05 16:32:00    1
2019-04-05 16:41:00    1
2019-04-07 17:53:00    1
2019-04-10 14:28:00    1
2019-04-20 15:39:00    1
2019-04-20 15:44:00    1
2019-04-23 15:54:00    2
2019-04-24 15:10:00    1
2019-04-26 16:40:00    1
2019-04-26 16:43:00    1
2019-04-30 16:11:00    1
2019-05-04 17:03:00    1
2019-05-28 15:46:00    1
2019-05-31 17:15:00    1
2019-06-06 15:13:00    1
2019-06-08 16:01:00    1
2019-06-09 17:06:00    1
2019-06-15 15:23:00    1
2019-06-24 15:16:00    1
2019-06-24 15:17:00    1
2019-06-28 15:40:00    1
2019-06-28 15:42:00    1
2019-06-29 16:20:00    1
2019-08-06 15:05:00    1
2019-08-06 15:46:00    1
2019-08-14 14:49:00    1
2019-08-16 16:32:00    1
2019-08-17 15:06:00    1
2019-08-21 15:16:00    1
2019-08-23 16:01:00    1
2019-08-23 16:02:00    1
2019-08-30 16:54:00    2
2019-08-31 16:56:00    2
2019-09-13 14:54:00    1


In [ ]:
#salvar em formato csv a tabela

valores_c1.to_csv('cliente1.csv')

In [ ]:
cliente1[(cliente1["object_type"]=="Reward")].sort_values("interacted_at")

id brand_id store_id  ... object_id object_type  value
66840   423913203        2     4319  ...        26      Reward    6.0
22791   468089599        2      376  ...        26      Reward    6.0
22794   468237384        2      376  ...        26      Reward    6.0
154672  533200499        2     4319  ...        26      Reward    6.0
50904   447322457        2     4319  ...        26      Reward    6.0
105460  513167358        2     4319  ...        26      Reward    6.0
8186    500000482        2     4319  ...        26      Reward    6.0
11235   502690120        2     4319  ...        26      Reward    6.0
38501   495621938        2     4319  ...        26      Reward    6.0
111836  515373176        2     4319  ...        26      Reward    6.0
118880  517883326        2     4319  ...        26      Reward    6.0
124028  520436462        2      376  ...        26      Reward    6.0
142430  526545606        2     4319  ...        26      Reward    6.0
176720  542972517        2     4319  ...        26      Reward    6.0
134574  523677554        2     4319  ...        26      Reward    6.0

[15 rows x 10 columns]

In [ ]:
#verificar clientes com mais interações na lojas



Cliente 2

In [ ]:
cliente2 = dt_sem_reviews.loc[dt_sem_reviews.user_id == "1711189"].sort_values('interacted_at') 

In [ ]:
valores_c2 = cliente2["interacted_at"].sort_values().to_csv('clitente2.csv')

valores_c2


In [ ]:
cliente2[(cliente2["object_type"]=="Reward")].sort_values("interacted_at")

id brand_id store_id  ... object_id object_type  value
152202  532009503        2     4828  ...        26      Reward    6.0
123896  520926544        2     4828  ...        26      Reward    6.0
104034  512716674        2     4828  ...        26      Reward    6.0
104035  512717156        2     4828  ...        26      Reward    6.0
24506   484516390        2     4828  ...        26      Reward    6.0
105740  513166971        2     4828  ...        26      Reward    6.0
7928    497712182        2     4828  ...        26      Reward    6.0
8345    500162258        2     4828  ...        26      Reward    6.0
131729  522533362        2     4828  ...        26      Reward    6.0
86907   507141439        2     4828  ...        26      Reward    6.0
97742   510794339        2     4828  ...        26      Reward    6.0
113824  516126280        2     4828  ...        26      Reward    6.0
127316  519797629        2     4828  ...        26      Reward    6.0
146570  528071121        2     4828  ...        26      Reward    6.0
167210  538484850        2     4828  ...        26      Reward    6.0
172311  541326574        2     4828  ...        26      Reward    6.0

[16 rows x 10 columns]

Cliente 3

In [ ]:
cliente3 = dt_sem_reviews.loc[dt_sem_reviews.user_id == "3846196"].sort_values('interacted_at')   

In [ ]:
valores_c3 = cliente3["interacted_at"].sort_values().to_csv('clitente3.csv')

valores_c3

In [ ]:
cliente3[(cliente3["object_type"]=="Reward")].sort_values("interacted_at")

id brand_id store_id  ... object_id object_type  value
61435   441011270        2      376  ...        26      Reward    6.0
51753   459410766        2      376  ...        26      Reward    6.0
26863   487575652        2      376  ...        26      Reward    6.0
86272   506704580        2      376  ...        26      Reward    6.0
114871  516506770        2      376  ...        26      Reward    6.0
133556  523428230        2      376  ...        26      Reward    6.0
162283  537054475        2      376  ...        26      Reward    6.0

[7 rows x 10 columns]

clientes que resgatam

In [ ]:
list_cliente_reward = dado[dado['object_type']== "Reward"]['user_id'].unique()

list_cliente_reward

array(['1652873', '9974693', '1634274', ..., '7142495', '11197479',
       '10707330'], dtype=object)

In [ ]:
vendas_reward = dado[dado["user_id"].isin(list_cliente_reward)]
vendas_reward

id brand_id store_id  ... object_id object_type  value
57      499349409        2      376  ...  55571501    Purchase   29.9
63      499438632        2      376  ...  55618189    Purchase   22.9
66      499441211        2      376  ...  55620529    Purchase   17.0
77      499461285        2      376  ...  55634172    Purchase   28.4
84      499472848        2      376  ...  55640856    Purchase   39.9
...           ...      ...      ...  ...       ...         ...    ...
178893  528592927        2      376  ...  69923636    Purchase   29.9
178897  528607778        2      376  ...  69931658    Purchase   23.4
178899  528610661        2      376  ...  69933318    Purchase   19.4
178913  528674129        2      376  ...  69968447    Purchase   28.4
178932  541516737        2     2375  ...  74294672    Purchase   17.0

[21853 rows x 10 columns]

In [ ]:
vendas_reward["id"]=vendas_reward["id"].astype(str)

vendas_reward["id"].count()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


21853

In [ ]:
vendas_reward["user_id"].value_counts()



4903322     58
3846196     55
1711189     53
9542884     51
3525314     49
            ..
4352798      1
10393742     1
8827903      1
4055055      1
4550137      1
Name: user_id, Length: 2342, dtype: int64

TEMOS 67151 MIL VENDAS DE 2342 mild CLIENTES QUE UTILIZARAM O SISTEMA DE REWARD

In [ ]:
dado["user_id"].value_counts()

4903322     58
3846196     55
1711189     53
9542884     51
3525314     49
            ..
9617313      1
11808422     1
9570151      1
11463843     1
9493398      1
Name: user_id, Length: 54743, dtype: int64

In [ ]:
dado["id"].value_counts()

537123093    1
516534302    1
436849895    1
528744970    1
489116004    1
            ..
489103690    1
501103546    1
538129433    1
533839252    1
496192118    1
Name: id, Length: 95200, dtype: int64

In [ ]:
21853/2342


9.330913748932536

In [ ]:
9.330913748932536/1.3997251960840442

6.66624689977523

In [ ]:

73347/52401


1.3997251960840442

CLIENTES QUE RESGATAM CONSOMEM 6X MAIS

In [ ]:
#clientes reagatam, data e frequencia

variavel_vendasrd = vendas_reward["interacted_at"].sort_values().unique()


variavel_vendasrd



array(['2019-01-04T00:00:00.000000000', '2019-01-04T00:01:00.000000000',
       '2019-01-04T00:21:00.000000000', ...,
       '2019-12-10T23:38:00.000000000', '2019-12-10T23:40:00.000000000',
       '2019-12-10T23:51:00.000000000'], dtype='datetime64[ns]')

In [ ]:
vendas_reward["interacted_at"].sort_values().to_csv('vendas.csv')

In [ ]:
vendas_reward.loc[(vendas_reward["object_type"]=="Reward")]["interacted_at"].sort_values().to_csv('rewards.csv')